x-base: &base
  build:
    context: .
    dockerfile: .docker/Dockerfile.dev
  stdin_open: true
  tty: true

services:
  db:
    image: postgres:latest
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    <<: *base
    command: bin/dev
    restart: on-failure
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    environment:
      RUBY_YJIT_ENABLE: 1
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    depends_on:
      - db

  # test:
  #   <<: *base
  #   restart: on-failure
  #   volumes:
  #     - .:/app:cached
  #   environment:
  #     RAILS_ENV: test


volumes:
  postgres_data:
