default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'db' } %>

development:
  <<: *default
  database: polyglot_development

test:
  <<: *default
  database: polyglot_test

production:
  <<: *default
  database: polyglot_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
