module FdcAdultCardsFr
  CONTENT = {
    "V0C0L0": "FR-FR",
    "V1C0L0": "Adultes",
    "V1C0L1": "Français - France",
    "V1C0L10": "Pour une version simplifiée du jeu, enlevez les cartes 10, 14, 15, 41.",
    "V1C0L11": "Réflexion",
    "V1C0L12": "Créativité & Synthèse",
    "V1C0L13": "Émotions",
    "V1C0L14": "Discussion",
    "V1C0L15": "Vous avez toutes les cartes en main",
    "V1C0L2": "FR-FR",
    "V1C0L3": "La Fresque du Climat",
    "V1C0L4": "Lot",
    "V1C0L5": "Comment y joue t-on ?",
    "V1C0L6": "Il vous faut un jeu de carte par équipe de 4 à 7 personnes, 2m² de papier, des crayons, une gomme, des feutres et du scotch.\n",
    "V1C0L7": "Le but du jeu est de mettre, en équipe, les cartes dans l’ordre des causes et des effets et de dessiner ces liens sous forme de flèches.\n",
    "V1C0L8": "Positionnez toutes les cartes d’un lot avant de passer au lot suivant.\n",
    "V1C0L9": "Timing : une heure et demi pour positionner toutes les cartes, 20 à 30 minutes pour décorer la fresque et présenter la synthèse, 10 minutes pour l’expression des émotions puis 45 minutes à 1 heure pour discuter des leviers d’action.\n",
    "V1C10L1": "Émissions d'aérosols",
    "V1C10L2": "Rien à voir avec les bombes aérosols.\nLes aérosols sont une pollution locale qui vient de la combustion imparfaite des énergies fossiles.  Ils sont mauvais pour la santé et ils ont par ailleurs une contribution négative au forçage radiatif (ils refroidissent le climat).",
    "V1C11L1": "Concentration en CO2 (ppm)",
    "V1C11L2": "Une fois que la moitié de nos émissions de CO2 a été captée par les puits naturels, l'autre moitié reste dans l'atmosphère.\nLa concentration en CO2 dans l'atmosphère est passée de 280 à 420 ppm (parties par millions) en 150 ans.",
    "V1C11L3": "280 ppm",
    "V1C11L4": "420 ppm",
    "V1C11L5": "400 ppm",
    "V1C11L6": "1100 ppm",
    "V1C12L1": "Puits de carbone",
    "V1C12L2": "La moitié du CO2 que nous émettons chaque année est absorbée par les puits de carbone : \n - la végétation pour 1/4 (via la photosynthèse) \n - l'océan pour 1/4 \n Le reste (1/2) reste dans l'atmosphère.",
    "V1C12L3": "Océan",
    "V1C12L4": "1/4",
    "V1C12L5": "Atmosphère",
    "V1C12L6": "1/2",
    "V1C12L7": "Photosynthèse",
    "V1C12L8": "1/4",
    "V1C12L9": "Partitionnement annuel du CO2 anthropogénique (GtC/an)",
    "V1C13L1": "Effet de serre additionnel",
    "V1C13L2": "L'effet de serre est naturel. D’ailleurs, le premier GES naturel est la vapeur d’eau.\nSans l'effet de serre, la planète serait 33°C plus froide. Mais le CO2 et les autres GES dus aux activités humaines augmentent cet effet de serre naturel ce qui réchauffe le climat.",
    "V1C13L3": "Insolation",
    "V1C13L4": "Réflexion",
    "V1C13L5": "Rayonnement infrarouge",
    "V1C13L6": "Effet de Serre",
    "V1C13L7": "15°C",
    "V1C13L8": "-18°C",
    "V1C14L1": "Bilan énergétique",
    "V1C14L10": "1%",
    "V1C14L11": "Contenu énergétique (ZJ)",
    "V1C14L2": "Ce graphique explique où va l’énergie qui s’accumule sur la terre à cause du forçage radiatif : elle réchauffe l’océan, fait fondre la glace, se dissipe dans le sol et réchauffe l’atmosphère.",
    "V1C14L3": "Océan",
    "V1C14L4": "Fonte des glaces",
    "V1C14L5": "Dissipation dans le sol",
    "V1C14L6": "Atmosphère",
    "V1C14L7": "91%",
    "V1C14L8": "3%",
    "V1C14L9": "5%",
    "V1C15L1": "Forçage radiatif",
    "V1C15L10": "Solar",
    "V1C15L11": "Black carbon on snow",
    "V1C15L12": "Contrails",
    "V1C15L13": "Stratospheric H2O",
    "V1C15L14": "Tropospheric O3",
    "V1C15L15": "Other WMGHG",
    "V1C15L16": "N2O",
    "V1C15L17": "CH4",
    "V1C15L18": "CO2",
    "V1C15L2": "Le forçage radiatif est la mesure du déséquilibre entre l'énergie qui arrive chaque seconde sur terre et celle qui repart.\nIl vaut 3,8 W/m2 (Watt par m2) pour l’effet de serre et - 1 W/m2 pour les aérosols, soit 2,8 W/m2 en tout.",
    "V1C15L20": "Land Use",
    "V1C15L21": "Aerosols (effet direct)",
    "V1C15L22": "Aerosols (effet indirect)",
    "V1C15L23": "Volcanic",
    "V1C15L3": "Effet de serre additionnel ",
    "V1C15L30": "Total anthropique",
    "V1C15L31": "Total",
    "V1C15L4": "Aérosols",
    "V1C15L5": "2,8 W/m²",
    "V1C16L1": "Fonte des glaciers",
    "V1C16L2": "Presque tous les glaciers ont perdu de la masse. Des centaines ont même déjà disparu. Or ces glaciers ont un rôle régulateur sur l'approvisionnement en eau douce.",
    "V1C17L1": "Hausse de la température de l'eau",
    "V1C17L2": "L'océan absorbe 91% de l’énergie qui s’accumule sur la Terre.\nEn se réchauffant, l’eau se dilate.",
    "V1C18L1": "Fonte de la banquise",
    "V1C18L2": "La fonte de la banquise n'est pas responsable de la montée des eaux (un glaçon qui fond dans du pastis ne fait pas déborder le verre). ",
    "V1C19L1": "Fonte des calottes glaciaires",
    "V1C19L2": "Les calottes glaciaires sont le Groënland et l'Antarctique. Si elles fondaient intégralement, cela représenterait une augmentation du niveau de la mer de 7 m pour le Groënland, et de 54 m pour l'Antarctique. Durant la dernière ère glaciaire, les calottes étaient si importantes que le niveau de la mer était 120 m plus bas qu'aujourd'hui.",
    "V1C19L3": "7 m",
    "V1C19L4": "54 m",
    "V1C1L1": "Activités humaines",
    "V1C1L2": "C'est là que tout commence…",
    "V1C20L1": "Perturbation du cycle de l'eau",
    "V1C20L2": "L'évaporation qui a lieu à la surface de l'océan augmente si l'eau et l'air se réchauffent.\nCela fait plus de nuages qui feront ensuite de la pluie. Mais si l’évaporation a lieu sur terre, cela assèche le sol.",
    "V1C20L3": "Evaporation",
    "V1C20L4": "Nuages",
    "V1C20L5": "Pluie",
    "V1C20L6": "Neige",
    "V1C20L7": "Rivières",
    "V1C20L8": "Infiltration",
    "V1C21L1": "Hausse de la température",
    "V1C21L2": "On parle ici de la température de l’air au sol, en moyenne sur la surface de la Terre. Elle a déjà augmenté de 1,2°C depuis 1900. Selon les scénarios d’émissions, elle aura augmenté de 1,5°C à 5°C d’ici 2100. Or, lors de la dernière période glaciaire (il y a 20.000 ans), elle était seulement 5°C plus basse qu’aujourd’hui... et la déglaciation a duré 10.000 ans !",
    "V1C21L3": "+ 1,2°C",
    "V1C21L4": "+ 1,5°C",
    "V1C21L5": "+ 5°C",
    "V1C21L6": "Changement de température de la surface mondiale par rapport à 1850-1900",
    "V1C21L7": "Observé",
    "V1C21L8": "Modélisé humains et naturels",
    "V1C21L9": "Modélisé naturels seuls (solaire et volcanique)",
    "V1C22L1": "Montée des eaux",
    "V1C22L2": "Depuis 1900, le niveau de l’océan a monté de 20 cm. Cela est dû à la dilatation de l'eau qui se réchauffe, la fonte des glaciers et la fonte des calottes.",
    "V1C22L3": "Variation de la moyenne mondiale du niveau des océans par rapport à 1900 (m)",
    "V1C22L4": "20 cm",
    "V1C22L5": "80 cm",
    "V1C22L6": "50 cm",
    "V1C22L7": "Scénario extrême, mais « qui ne peut pas être exclu »",
    "V1C23L1": "Problèmes de calcification",
    "V1C23L2": "Si le pH baisse, la formation de calcaire devient plus difficile, notamment pour les coquilles.",
    "V1C24L1": "Acidification de l'océan",
    "V1C24L2": "Quand le CO2 se dissout dans l'océan, il se transforme en des ions qui ont pour effet d'acidifier l'océan (le pH baisse).",
    "V1C24L3": "Acidification de l’océan en fonction des scénarios SSP (pH)",
    "V1C25L1": "Biodiversité terrestre",
    "V1C25L2": "Les causes de l’érosion de la biodiversité sont : la destruction des habitats, la surexploitation des espèces sauvages, la pollution, le changement climatique et l’introduction d’espèces exotiques envahissantes.\nLe changement des conditions de vie des espèces (température, cycle de l’eau) les force à migrer et à adapter leur mode de vie.",
    "V1C26L1": "Crues",
    "V1C26L2": "La perturbation du cycle de l'eau peut amener plus d'eau ou moins d’eau.\nPlus d'eau, cela peut engendrer des crues (inondations dans les terres).\nAvec l'urbanisation ou si le sol a été durci par une sécheresse, c'est pire car l'eau ruisselle.",
    "V1C27L1": "Biodiversité marine",
    "V1C27L2": "Ptéropodes et coccolithophores étant à la base de la chaîne alimentaire, leur disparition menace toute la biodiversité marine.\nLa biodiversité marine est fragilisée par le réchauffement de l'eau ainsi que par la surexploitation des réserves halieutiques.",
    "V1C28L1": "Vecteurs de maladie",
    "V1C28L2": "Avec le réchauffement, les animaux migrent. Or, certains sont des vecteurs de maladie et peuvent atteindre des zones où les populations ne sont pas immunisées contre ces maladies.",
    "V1C29L1": "Ptéropodes et coccolithophores",
    "V1C29L2": "Les ptéropodes sont du zooplancton et les coccolithophores du phytoplancton. Ces micro-organismes ont une coquille en calcaire.",
    "V1C2L1": "Industrie",
    "V1C2L2": "L'industrie utilise des énergies fossiles et de l'électricité.\nElle représente 40% des Gaz à Effet de Serre (GES).",
    "V1C30L1": "Sécheresses",
    "V1C30L2": "La perturbation du cycle de l'eau peut amener plus ou moins d'eau.\nMoins d'eau, c'est une sécheresse.\nOn estime ainsi que les sécheresses pourraient se multiplier à l’avenir.",
    "V1C31L1": "Ressources en eau douce",
    "V1C31L2": "Les ressources en eau douce sont affectées par les changements de précipitation et la disparition des glaciers qui jouent un rôle régulateur du débit des cours d'eau.",
    "V1C32L1": "Baisse des rendements agricoles",
    "V1C32L2": "La production agricole peut être affectée par la température, les sécheresses, les évènements extrêmes, les inondations et les submersions (ex : delta du Nil).",
    "V1C33L1": "Submersions",
    "V1C33L2": "Cyclones et perturbations amènent du vent (donc des vagues) et des basses pressions.\nOr, chaque hectopascal en moins, c’est 1 cm d’eau en plus. Ils peuvent donc occasionner des submersions (inondations côtières) qui sont aggravées par l’augmentation du niveau de l’océan.",
    "V1C34L1": "Cyclones",
    "V1C34L2": "Les cyclones s’alimentent de l’énergie des eaux chaudes à la surface de l’océan.\nLeur puissance a augmenté à cause du changement climatique.",
    "V1C35L1": "Incendies",
    "V1C35L2": "Les incendies sont facilités par les sécheresses et les canicules.\nIls émettent du CO2 au même titre que la déforestation. Ceci constitue une boucle de rétroaction.",
    "V1C36L1": "Canicules",
    "V1C36L2": "Les canicules vont devenir plus fréquentes et plus intenses. La combinaison de la température et de l'humidité peut conduire à des conditions mortelles pour les êtres humains. On prévoit une augmentation du nombre de jours durant lesquels ces conditions mortelles sont réunies.",
    "V1C37L1": "Famines",
    "V1C37L2": "Les famines peuvent être occasionnées par la baisse des rendements agricoles et la réduction de la biodiversité marine.",
    "V1C38L1": "Santé humaine",
    "V1C38L2": "Famines, déplacement des vecteurs de maladie, canicules et conflits armés peuvent affecter la santé humaine.",
    "V1C39L1": "Déplacement de populations",
    "V1C39L2": "Les conséquences du changement climatique vont inévitablement rendre certains écosystèmes inhabitables  pour les humains et forcer les populations à se déplacer. ",
    "V1C3L1": "Utilisation des bâtiments",
    "V1C3L2": "L’utilisation du bâtiment (logement et services) utilise des énergies fossiles et de l'électricité.\nCela représente 20% des Gaz à Effet de Serre (GES).",
    "V1C40L1": "Conflits armés",
    "V1C40L2": "C'est comme ça qu'il faudrait éviter que ça finisse…",
    "V1C41L1": "Permafrost",
    "V1C41L2": "Le permafrost désigne le sol gelé en permanence. On constate qu’il commence à dégeler, relâchant dans l’air du CO2 et du méthane, suite à la décomposition de la matière organique qui était jusque-là gelée. Cela constitue une boucle de rétroaction. ",
    "V1C42L1": "Accroissement des inégalités",
    "V1C42L2": "Le changement climatique renforce les inégalités sociales et économiques entre les individus, entre les pays et entre les générations.\nPour ne pas aggraver ces inégalités, les politiques climatiques doivent être justes et équitables.",
    "V1C4L1": "Transport",
    "V1C4L2": "Le secteur du transport est très dépendant du pétrole.\nIl représente 15% des émissions de gaz à effet de serre.",
    "V1C5L1": "Utilisation des énergies fossiles",
    "V1C5L11": "SSP1-1.9",
    "V1C5L12": "SSP1-2.6",
    "V1C5L13": "SSP2-4.5",
    "V1C5L14": "SSP3-7.0",
    "V1C5L15": "SSP5-8.5",
    "V1C5L2": "Les énergies fossiles sont le charbon, le pétrole et le gaz. Elles sont utilisées principalement dans les bâtiments, le transport et dans l'industrie. Elles émettent du CO2 lors de la combustion.",
    "V1C5L3": "40 GtCO2/an   ",
    "V1C5L4": "Milliards de tonnes de CO2 par an",
    "V1C5L5": "Emissions de CO2 des énergies fossiles",
    "V1C5L6": "2060",
    "V1C5L7": "2080",
    "V1C6L1": "Déforestation",
    "V1C6L2": "La déforestation consiste à couper ou brûler des arbres au-delà de la capacité de renouvellement de la forêt.\nElle est liée à 80% à l’agriculture.\nEn plus d'émettre du CO2, elle prive les espèces locales de leur habitat.",
    "V1C7L1": "Émissions de CO2",
    "V1C7L2": "Le CO2 est le premier gaz à effet de serre anthropique (c'est à dire émis par les activités humaines). Les émissions de CO2 viennent de la combustion des énergies fossiles et de la déforestation.",
    "V1C7L3": "Energies fossiles",
    "V1C7L4": "Déforestation",
    "V1C7L5": "Emissions annuelles de CO2 anthropogénique (GtC/an)",
    "V1C8L1": "Agriculture",
    "V1C8L2": "L'agriculture est responsable d'émissions de CO2 (déforestation), de méthane (bovins, rizières), et de protoxyde d'azote (engrais). En tout, au niveau mondial, l'agriculture est responsable de 25% des Gaz à Effet de Serre. ",
    "V1C999L2": "La Fresque du Climat a été créée par Cédric Ringenbach.\nSa diffusion est assurée par l’association La Fresque du Climat.",
    "V1C999L3": "La participation à un atelier La Fresque du Climat puis à une formation à l’animation est nécessaire pour animer une Fresque du Climat.\nLa licence d'utilisation est Creative Commons BY-NC-ND pour une utilisation non professionnelle.\n",
    "V1C999L4": "Tout usage commercial ou dans un usage dans la sphère interne d’une entreprise, sans intervention de prestataires, sont soumis à des droits d’utilisation.\nLa licence complète est disponible ici : fresqueduclimat.org/licence.\nLes droits d’utilisation sont à reverser sur : fresqueduclimat.org/droits.",
    "V1C999L5": "L’auteur Cédric Ringenbach \n+33 7 54 57 86 65\nclimate.fresk@ringenbach.com",
    "V1C999L6": "L’association La Fresque du Climat\nfresqueduclimat.org",
    "V1C999L7": "Scannez pour nous rejoindre !",
    "V1C999L8": "FR-FR",
    "V1C999L9": "Français",
    "V1C999L90": "Source : GIEC",
    "V1C999L91": "Imprimé en France sur du papier 100% recyclé.",
    "V1C999L92": "Source : GIEC",
    "V1C999L93": "Source : GIEC",
    "V1C999L94": "Source : GIEC",
    "V1C999L95": "Source : GIEC",
    "V1C999L96": "Source : GIEC",
    "V1C999L97": "Source : GIEC",
    "V1C999L98": "Source : GIEC",
    "V1C999L99": "Source : GIEC",
    "V1C99L1": "Correction",
    "V1C99L9": "Correction",
    "V1C9L1": "Émissions d'autres GES",
    "V1C9L2": "Le CO2 n'est pas le seul Gaz à Effet de Serre. Il y a aussi le méthane (CH4) et le protoxyde d'azote (N2O) (qui viennent en très grande partie de l'agriculture), ainsi que quelques autres."
  }.freeze
end
